data$airport <-data$Origin

data$airport[data$airport == "ABE"] = 'Lehigh Valley International Airport'
data$airport[data$airport == "ABI"] = 'Abilene Regional Airport'
data$airport[data$airport == "ABQ"] = 'Albuquerque International Sunport'
data$airport[data$airport == "ABR"] = 'Aberdeen Regional Airport'
data$airport[data$airport == "ABY"] = 'Southwest Georgia Regional Airport'
data$airport[data$airport == "ACK"] = 'Nantucket Memorial Airport'
data$airport[data$airport == "ACT"] = 'Waco Regional Airport'
data$airport[data$airport == "ACV"] = 'Arcata Airport'
data$airport[data$airport == "ACY"] = 'Atlantic City International Airport'
data$airport[data$airport == "ADK"] = 'Adak Airport'
data$airport[data$airport == "ADQ"] = 'Kodiak Airport'
data$airport[data$airport == "AEX"] = 'Alexandria International Airport'
data$airport[data$airport == "AGS"] = 'Augusta Regional Airport (Bush Field)'
data$airport[data$airport == "AKN"] = 'King Salmon Airport'
data$airport[data$airport == "ALB"] = 'Albany International Airport'
data$airport[data$airport == "ALO"] = 'Waterloo Regional Airport'
data$airport[data$airport == "AMA"] = 'Rick Husband Amarillo International Airport'
data$airport[data$airport == "ANC"] = 'Ted Stevens Anchorage International Airport'
data$airport[data$airport == "APN"] = 'Alpena County Regional Airport'
data$airport[data$airport == "ASE"] = 'Aspen-Pitkin County Airport'
data$airport[data$airport == "ATL"] = 'Hartsfield-Jackson Atlanta International Airport'
data$airport[data$airport == "ATW"] = 'Appleton International Airport'
data$airport[data$airport == "AUS"] = 'Austin-Bergstrom International Airport'
data$airport[data$airport == "AVL"] = 'Asheville Regional Airport'
data$airport[data$airport == "AVP"] = 'Wilkes-Barre/Scranton International Airport'
data$airport[data$airport == "AZO"] = 'Kalamazoo/Battle Creek International Airport'
data$airport[data$airport == "BDL"] = 'Bradley International Airport'
data$airport[data$airport == "BET"] = 'Bethel Airport'
data$airport[data$airport == "BFL"] = 'Meadows Field'
data$airport[data$airport == "BGM"] = 'Greater Binghamton Airport'
data$airport[data$airport == "BGR"] = 'Bangor International Airport'
data$airport[data$airport == "BHM"] = 'Birmingham-Shuttlesworth International Airport'
data$airport[data$airport == "BIL"] = 'Billings Logan International Airport'
data$airport[data$airport == "BIS"] = 'Bismarck Municipal Airport'
data$airport[data$airport == "BJI"] = 'Bemidji Regional Airport'
data$airport[data$airport == "BLI"] = 'Bellingham International Airport'
data$airport[data$airport == "BMI"] = 'Central Illinois Regional Airport at Bloomington-Normal'
data$airport[data$airport == "BNA"] = 'Nashville International Airport'
data$airport[data$airport == "BOI"] = 'Boise Airport (Boise Air Terminal)'
data$airport[data$airport == "BOS"] = 'Gen. Edward Lawrence Logan International Airport'
data$airport[data$airport == "BPT"] = 'Jack Brooks Regional Airport (Southeast Texas Regional)'
data$airport[data$airport == "BQK"] = 'Brunswick Golden Isles Airport'
data$airport[data$airport == "BQN"] = 'Rafael Hernández Airport'
data$airport[data$airport == "BRD"] = 'Brainerd Lakes Regional Airport'
data$airport[data$airport == "BRO"] = 'Brownsville/South Padre Island International Airport'
data$airport[data$airport == "BRW"] = 'Wiley Post-Will Rogers Memorial Airport'
data$airport[data$airport == "BTM"] = 'Bert Mooney Airport'
data$airport[data$airport == "BTR"] = 'Baton Rouge Metropolitan Airport'
data$airport[data$airport == "BTV"] = 'Burlington International Airport'
data$airport[data$airport == "BUF"] = 'Buffalo Niagara International Airport'
data$airport[data$airport == "BUR"] = 'Bob Hope Airport (Hollywood Burbank Airport)'
data$airport[data$airport == "BWI"] = 'Baltimore-Washington International Airport'
data$airport[data$airport == "BZN"] = 'Bozeman Yellowstone International Airport (Gallatin Field Airport)'
data$airport[data$airport == "CAE"] = 'Columbia Metropolitan Airport'
data$airport[data$airport == "CAK"] = 'Akron-Canton Regional Airport'
data$airport[data$airport == "CDC"] = 'Cedar City Regional Airport'
data$airport[data$airport == "CDV"] = 'Merle K. (Mudhole) Smith Airport'
data$airport[data$airport == "CEC"] = 'Del Norte County Airport (Jack McNamara Field)'
data$airport[data$airport == "CHA"] = 'Chattanooga Metropolitan Airport (Lovell Field)'
data$airport[data$airport == "CHO"] = 'Charlottesville-Albemarle Airport'
data$airport[data$airport == "CHS"] = 'Charleston International Airport/Charleston AFB'
data$airport[data$airport == "CID"] = 'The Eastern Iowa Airport'
data$airport[data$airport == "CIU"] = 'Chippewa County International Airport'
data$airport[data$airport == "CLD"] = 'McClellan-Palomar Airport'
data$airport[data$airport == "CLE"] = 'Cleveland Hopkins International Airport'
data$airport[data$airport == "CLL"] = 'Easterwood Airport'
data$airport[data$airport == "CLT"] = 'Charlotte Douglas International Airport'
data$airport[data$airport == "CMH"] = 'Port Columbus International Airport'
data$airport[data$airport == "CMI"] = 'University of Illinois - Willard Airport'
data$airport[data$airport == "CMX"] = 'Houghton County Memorial Airport'
data$airport[data$airport == "CNY"] = 'Canyonlands Field'
data$airport[data$airport == "COD"] = 'Yellowstone Regional Airport'
data$airport[data$airport == "COS"] = 'City of Colorado Springs Municipal Airport'
data$airport[data$airport == "COU"] = 'Columbia Regional Airport'
data$airport[data$airport == "CPR"] = 'Natrona County International Airport'
data$airport[data$airport == "CRP"] = 'Corpus Christi International Airport'
data$airport[data$airport == "CRW"] = 'Yeager Airport'
data$airport[data$airport == "CSG"] = 'Columbus Metropolitan Airport'
data$airport[data$airport == "CVG"] = 'Cincinnati/Northern Kentucky International Airport'
data$airport[data$airport == "CWA"] = 'Central Wisconsin Airport'
data$airport[data$airport == "DAB"] = 'Daytona Beach International Airport'
data$airport[data$airport == "DAL"] = 'Dallas Love Field'
data$airport[data$airport == "DAY"] = 'James M. Cox Dayton International Airport'
data$airport[data$airport == "DBQ"] = 'Dubuque Regional Airport'
data$airport[data$airport == "DCA"] = 'Ronald Reagan Washington National Airport'
data$airport[data$airport == "DEN"] = 'Denver International Airport'
data$airport[data$airport == "DFW"] = 'Dallas/Fort Worth International Airport'
data$airport[data$airport == "DHN"] = 'Dothan Regional Airport'
data$airport[data$airport == "DIK"] = 'Dickinson Theodore Roosevelt Regional Airport'
data$airport[data$airport == "DLG"] = 'Dillingham Airport'
data$airport[data$airport == "DLH"] = 'Duluth International Airport'
data$airport[data$airport == "DRO"] = 'Durango-La Plata County Airport'
data$airport[data$airport == "DSM"] = 'Des Moines International Airport'
data$airport[data$airport == "DTW"] = 'Detroit Metropolitan Airport'
data$airport[data$airport == "DVL"] = 'Devils Lake Regional Airport'
data$airport[data$airport == "EAU"] = 'Chippewa Valley Regional Airport'
data$airport[data$airport == "ECP"] = 'Northwest Florida Beaches International Airport'
data$airport[data$airport == "EGE"] = 'Eagle County Regional Airport'
data$airport[data$airport == "EKO"] = 'Elko Regional Airport'
data$airport[data$airport == "ELM"] = 'Elmira/Corning Regional Airport'
data$airport[data$airport == "ELP"] = 'El Paso International Airport'
data$airport[data$airport == "ERI"] = 'Erie International Airport'
data$airport[data$airport == "ESC"] = 'Delta County Airport'
data$airport[data$airport == "EUG"] = 'Eugene Airport (Mahlon Sweet Field)'
data$airport[data$airport == "EVV"] = 'Evansville Regional Airport'
data$airport[data$airport == "EWN"] = 'Coastal Carolina Regional Airport (Craven County Regional)'
data$airport[data$airport == "EWR"] = 'Newark Liberty International Airport'
data$airport[data$airport == "EYW"] = 'Key West International Airport'
data$airport[data$airport == "FAI"] = 'Fairbanks International Airport'
data$airport[data$airport == "FAR"] = 'Hector International Airport'
data$airport[data$airport == "FAT"] = 'Fresno Yosemite International Airport'
data$airport[data$airport == "FAY"] = 'Fayetteville Regional Airport'
data$airport[data$airport == "FCA"] = 'Glacier Park International Airport'
data$airport[data$airport == "FLG"] = 'Flagstaff Pulliam Airport'
data$airport[data$airport == "FLL"] = 'Fort Lauderdale-Hollywood International Airport'
data$airport[data$airport == "FNT"] = 'Bishop International Airport'
data$airport[data$airport == "FSD"] = 'Sioux Falls Regional Airport'
data$airport[data$airport == "FSM"] = 'Fort Smith Regional Airport'
data$airport[data$airport == "FWA"] = 'Fort Wayne International Airport'
data$airport[data$airport == "GCC"] = 'Gillette-Campbell County Airport'
data$airport[data$airport == "GCK"] = 'Garden City Regional Airport'
data$airport[data$airport == "GEG"] = 'Spokane International Airport'
data$airport[data$airport == "GFK"] = 'Grand Forks International Airport'
data$airport[data$airport == "GGG"] = 'East Texas Regional Airport'
data$airport[data$airport == "GJT"] = 'Grand Junction Regional Airport (Walker Field)'
data$airport[data$airport == "GNV"] = 'Gainesville Regional Airport'
data$airport[data$airport == "GPT"] = 'Gulfport-Biloxi International Airport'
data$airport[data$airport == "GRB"] = 'Green Bay-Austin Straubel International Airport'
data$airport[data$airport == "GRI"] = 'Central Nebraska Regional Airport'
data$airport[data$airport == "GRK"] = 'Killeen-Fort Hood Regional Airport'
data$airport[data$airport == "GRR"] = 'Gerald R. Ford International Airport'
data$airport[data$airport == "GSO"] = 'Piedmont Triad International Airport'
data$airport[data$airport == "GSP"] = 'Greenville-Spartanburg International Airport'
data$airport[data$airport == "GST"] = 'Gustavus Airport'
data$airport[data$airport == "GTF"] = 'Great Falls International Airport'
data$airport[data$airport == "GTR"] = 'Golden Triangle Regional Airport'
data$airport[data$airport == "GUC"] = 'Gunnison-Crested Butte Regional Airport'
data$airport[data$airport == "GUM"] = 'Guam International Airport'
data$airport[data$airport == "HDN"] = 'Yampa Valley Airport (Yampa Valley Regional)'
data$airport[data$airport == "HIB"] = 'Range Regional Airport (Chisholm-Hibbing Airport)'
data$airport[data$airport == "HLN"] = 'Helena Regional Airport'
data$airport[data$airport == "HNL"] = 'Honolulu International Airport'
data$airport[data$airport == "HOB"] = 'Lea County Regional Airport'
data$airport[data$airport == "HOU"] = 'William P. Hobby Airport'
data$airport[data$airport == "HPN"] = 'Westchester County Airport'
data$airport[data$airport == "HRL"] = 'Valley International Airport'
data$airport[data$airport == "HSV"] = 'Huntsville International Airport'
data$airport[data$airport == "HYA"] = 'Barnstable Municipal Airport'
data$airport[data$airport == "HYS"] = 'Hays Regional Airport'
data$airport[data$airport == "IAD"] = 'Washington Dulles International Airport'
data$airport[data$airport == "IAG"] = 'Niagara Falls International Airport'
data$airport[data$airport == "IAH"] = 'George Bush Intercontinental Airport'
data$airport[data$airport == "ICT"] = 'Wichita Dwight D. Eisenhower National Airport (Wichita Mid-Continent Airport)'
data$airport[data$airport == "IDA"] = 'Idaho Falls Regional Airport'
data$airport[data$airport == "ILG"] = 'Wilmington Airport'
data$airport[data$airport == "ILM"] = 'Wilmington International Airport'
data$airport[data$airport == "IMT"] = 'Ford Airport'
data$airport[data$airport == "IND"] = 'Indianapolis International Airport'
data$airport[data$airport == "INL"] = 'Falls International Airport'
data$airport[data$airport == "ISN"] = 'Sloulin Field International Airport'
data$airport[data$airport == "ISP"] = 'Long Island MacArthur Airport'
data$airport[data$airport == "ITH"] = 'Ithaca Tompkins Regional Airport'
data$airport[data$airport == "ITO"] = 'Hilo International Airport'
data$airport[data$airport == "JAC"] = 'Jackson Hole Airport'
data$airport[data$airport == "JAN"] = 'Jackson-Evers International Airport'
data$airport[data$airport == "JAX"] = 'Jacksonville International Airport'
data$airport[data$airport == "JFK"] = 'John F. Kennedy International Airport (New York International Airport)'
data$airport[data$airport == "JLN"] = 'Joplin Regional Airport'
data$airport[data$airport == "JMS"] = 'Jamestown Regional Airport'
data$airport[data$airport == "JNU"] = 'Juneau International Airport'
data$airport[data$airport == "KOA"] = 'Kona International Airport at Keahole'
data$airport[data$airport == "KTN"] = 'Ketchikan International Airport'
data$airport[data$airport == "LAN"] = 'Capital Region International Airport ( Lansing Capital City)'
data$airport[data$airport == "LAR"] = 'Laramie Regional Airport'
data$airport[data$airport == "LAS"] = 'McCarran International Airport'
data$airport[data$airport == "LAW"] = 'Lawton-Fort Sill Regional Airport'
data$airport[data$airport == "LAX"] = 'Los Angeles International Airport'
data$airport[data$airport == "LBB"] = 'Lubbock Preston Smith International Airport'
data$airport[data$airport == "LBE"] = 'Arnold Palmer Regional Airport'
data$airport[data$airport == "LCH"] = 'Lake Charles Regional Airport'
data$airport[data$airport == "LEX"] = 'Blue Grass Airport'
data$airport[data$airport == "LFT"] = 'Lafayette Regional Airport'
data$airport[data$airport == "LGA"] = 'LaGuardia Airport (Marine Air Terminal)'
data$airport[data$airport == "LGB"] = 'Long Beach Airport (Daugherty Field)'
data$airport[data$airport == "LIH"] = 'Lihue Airport'
data$airport[data$airport == "LIT"] = 'Bill and Hillary Clinton National Airport (Adams Field)'
data$airport[data$airport == "LNK"] = 'Lincoln Airport (Lincoln Municipal)'
data$airport[data$airport == "LRD"] = 'Laredo International Airport'
data$airport[data$airport == "LSE"] = 'La Crosse Regional Airport'
data$airport[data$airport == "LWS"] = 'Lewiston-Nez Perce County Airport'
data$airport[data$airport == "MAF"] = 'Midland International Airport'
data$airport[data$airport == "MBS"] = 'MBS International Airport'
data$airport[data$airport == "MCI"] = 'Kansas City International Airport'
data$airport[data$airport == "MCO"] = 'Orlando International Airport'
data$airport[data$airport == "MDT"] = 'Harrisburg International Airport'
data$airport[data$airport == "MDW"] = 'Chicago Midway International Airport'
data$airport[data$airport == "MEI"] = 'Meridian Regional Airport'
data$airport[data$airport == "MEM"] = 'Memphis International Airport'
data$airport[data$airport == "MFE"] = 'McAllen-Miller International Airport (McAllen Miller International)'
data$airport[data$airport == "MFR"] = 'Rogue Valley International Airport'
data$airport[data$airport == "MGM"] = 'Montgomery Regional Airport'
data$airport[data$airport == "MHK"] = 'Manhattan Regional Airport'
data$airport[data$airport == "MHT"] = 'Manchester-Boston Regional Airport'
data$airport[data$airport == "MIA"] = 'Miami International Airport'
data$airport[data$airport == "MKE"] = 'General Mitchell International Airport'
data$airport[data$airport == "MKG"] = 'Muskegon County Airport'
data$airport[data$airport == "MLB"] = 'Melbourne International Airport'
data$airport[data$airport == "MLI"] = 'Quad City International Airport'
data$airport[data$airport == "MLU"] = 'Monroe Regional Airport'
data$airport[data$airport == "MMH"] = 'Mammoth Yosemite Airport'
data$airport[data$airport == "MOB"] = 'Mobile Regional Airport'
data$airport[data$airport == "MOT"] = 'Minot International Airport'
data$airport[data$airport == "MQT"] = 'Sawyer International Airport'
data$airport[data$airport == "MRY"] = 'Monterey Regional Airport (Monterey Peninsula Airport)'
data$airport[data$airport == "MSN"] = 'Dane County Regional Airport'
data$airport[data$airport == "MSO"] = 'Missoula International Airport'
data$airport[data$airport == "MSP"] = 'Minneapolis-Saint Paul International Airport'
data$airport[data$airport == "MSY"] = 'Louis Armstrong New Orleans International Airport'
data$airport[data$airport == "MTJ"] = 'Montrose Regional Airport'
data$airport[data$airport == "MVY"] = 'Martha's Vineyard Airport'
data$airport[data$airport == "MYR"] = 'Myrtle Beach International Airport'
data$airport[data$airport == "OAJ"] = 'Albert J. Ellis Airport'
data$airport[data$airport == "OAK"] = 'Oakland International Airport'
data$airport[data$airport == "OGG"] = 'Kahului Airport'
data$airport[data$airport == "OKC"] = 'Will Rogers World Airport'
data$airport[data$airport == "OMA"] = 'Eppley Airfield'
data$airport[data$airport == "OME"] = 'Nome Airport'
data$airport[data$airport == "ONT"] = 'Ontario International Airport'
data$airport[data$airport == "ORD"] = 'Chicago O'Hare International Airport'
data$airport[data$airport == "ORF"] = 'Norfolk International Airport'
data$airport[data$airport == "ORH"] = 'Worcester Regional Airport'
data$airport[data$airport == "OTH"] = 'Southwest Oregon Regional Airport (North Bend Municipal)'
data$airport[data$airport == "OTZ"] = 'Ralph Wien Memorial Airport'
data$airport[data$airport == "PAH"] = 'Barkley Regional Airport'
data$airport[data$airport == "PBG"] = 'Plattsburgh International Airport'
data$airport[data$airport == "PBI"] = 'Palm Beach International Airport'
data$airport[data$airport == "PDX"] = 'Portland International Airport'
data$airport[data$airport == "PHF"] = 'Newport News/Williamsburg International Airport'
data$airport[data$airport == "PHL"] = 'Philadelphia International Airport'
data$airport[data$airport == "PHX"] = 'Phoenix Sky Harbor International Airport'
data$airport[data$airport == "PIA"] = 'General Wayne A. Downing Peoria International Airport'
data$airport[data$airport == "PIB"] = 'Hattiesburg-Laurel Regional Airport'
data$airport[data$airport == "PIH"] = 'Pocatello Regional Airport'
data$airport[data$airport == "PIT"] = 'Pittsburgh International Airport'
data$airport[data$airport == "PLN"] = 'Pellston Regional Airport of Emmet County'
data$airport[data$airport == "PNS"] = 'Pensacola International Airport (Pensacola Gulf Coast Regional Airport)'
data$airport[data$airport == "PPG"] = 'Pago Pago International Airport (Tafuna Airport)'
data$airport[data$airport == "PSC"] = 'Tri-Cities Airport'
data$airport[data$airport == "PSE"] = 'Mercedita Airport'
data$airport[data$airport == "PSG"] = 'Petersburg James A. Johnson Airport'
data$airport[data$airport == "PSP"] = 'Palm Springs International Airport'
data$airport[data$airport == "PUB"] = 'Pueblo Memorial Airport'
data$airport[data$airport == "PVD"] = 'Theodore Francis Green State Airport'
data$airport[data$airport == "PWM"] = 'Portland International Jetport'
data$airport[data$airport == "RAP"] = 'Rapid City Regional Airport'
data$airport[data$airport == "RDD"] = 'Redding Municipal Airport'
data$airport[data$airport == "RDM"] = 'Redmond Municipal Airport (Roberts Field)'
data$airport[data$airport == "RDU"] = 'Raleigh-Durham International Airport'
data$airport[data$airport == "RHI"] = 'Rhinelander-Oneida County Airport'
data$airport[data$airport == "RIC"] = 'Richmond International Airport'
data$airport[data$airport == "RKS"] = 'Rock Springs-Sweetwater County Airport'
data$airport[data$airport == "RNO"] = 'Reno/Tahoe International Airport'
data$airport[data$airport == "ROA"] = 'Roanoke Regional Airport (Woodrum Field)'
data$airport[data$airport == "ROC"] = 'Greater Rochester International Airport'
data$airport[data$airport == "ROW"] = 'Roswell International Air Center'
data$airport[data$airport == "RST"] = 'Rochester International Airport'
data$airport[data$airport == "RSW"] = 'Southwest Florida International Airport'
data$airport[data$airport == "SAF"] = 'Santa Fe Municipal Airport'
data$airport[data$airport == "SAN"] = 'San Diego International Airport (Lindbergh Field)'
data$airport[data$airport == "SAT"] = 'San Antonio International Airport'
data$airport[data$airport == "SAV"] = 'Savannah/Hilton Head International Airport'
data$airport[data$airport == "SBA"] = 'Santa Barbara Municipal Airport (Santa Barbara Airport)'
data$airport[data$airport == "SBN"] = 'South Bend International Airport (South Bend Regional)'
data$airport[data$airport == "SBP"] = 'San Luis Obispo County Regional Airport (McChesney Field)'
data$airport[data$airport == "SCC"] = 'Deadhorse Airport (Prudhoe Bay Airport)'
data$airport[data$airport == "SCE"] = 'University Park Airport'
data$airport[data$airport == "SDF"] = 'Louisville International Airport (Standiford Field)'
data$airport[data$airport == "SEA"] = 'Seattle-Tacoma International Airport'
data$airport[data$airport == "SFO"] = 'San Francisco International Airport'
data$airport[data$airport == "SGF"] = 'Springfield-Branson National Airport'
data$airport[data$airport == "SGU"] = 'St. George Regional Airport'
data$airport[data$airport == "SHV"] = 'Shreveport Regional Airport'
data$airport[data$airport == "SIT"] = 'Sitka Rocky Gutierrez Airport'
data$airport[data$airport == "SJC"] = 'Norman Y. Mineta San José International Airport'
data$airport[data$airport == "SJT"] = 'San Angelo Regional Airport (Mathis Field)'
data$airport[data$airport == "SJU"] = 'Luis Muñoz Marín International Airport'
data$airport[data$airport == "SLC"] = 'Salt Lake City International Airport'
data$airport[data$airport == "SMF"] = 'Sacramento International Airport'
data$airport[data$airport == "SMX"] = 'Santa Maria Public Airport (Capt G. Allan Hancock Field)'
data$airport[data$airport == "SNA"] = 'John Wayne Airport (Orange County Airport)'
data$airport[data$airport == "SPI"] = 'Abraham Lincoln Capital Airport'
data$airport[data$airport == "SPS"] = 'Wichita Falls Municipal Airport/Sheppard AFB'
data$airport[data$airport == "SRQ"] = 'Sarasota-Bradenton International Airport'
data$airport[data$airport == "STC"] = 'St. Cloud Regional Airport'
data$airport[data$airport == "STL"] = 'St. Louis International Airport at Lambert Field'
data$airport[data$airport == "STT"] = 'Cyril E. King Airport'
data$airport[data$airport == "STX"] = 'Henry E. Rohlsen Airport'
data$airport[data$airport == "SUN"] = 'Friedman Memorial Airport'
data$airport[data$airport == "SUX"] = 'Sioux Gateway Airport'
data$airport[data$airport == "SWF"] = 'Stewart International Airport'
data$airport[data$airport == "SYR"] = 'Syracuse Hancock International Airport'
data$airport[data$airport == "TLH"] = 'Tallahassee International Airport'
data$airport[data$airport == "TOL"] = 'Toledo Express Airport'
data$airport[data$airport == "TPA"] = 'Tampa International Airport'
data$airport[data$airport == "TRI"] = 'Tri-Cities Regional Airport'
data$airport[data$airport == "TTN"] = 'Trenton Mercer Airport'
data$airport[data$airport == "TUL"] = 'Tulsa International Airport'
data$airport[data$airport == "TUS"] = 'Tucson International Airport'
data$airport[data$airport == "TVC"] = 'Cherry Capital Airport'
data$airport[data$airport == "TWF"] = 'Magic Valley Regional Airport (Joslin Field)'
data$airport[data$airport == "TXK"] = 'Texarkana Regional Airport (Webb Field)'
data$airport[data$airport == "TYR"] = 'Tyler Pounds Regional Airport'
data$airport[data$airport == "TYS"] = 'McGhee Tyson Airport'
data$airport[data$airport == "UST"] = 'Northeast Florida Regional Airport (St. Augustine Airport)'
data$airport[data$airport == "VEL"] = 'Valdez Airport'
data$airport[data$airport == "VLD"] = 'Valdosta Regional Airport'
data$airport[data$airport == "VPS"] = 'Destin-Fort Walton Beach Airport/Eglin AFB'
data$airport[data$airport == "WRG"] = 'Wrangell Airport'
data$airport[data$airport == "WYS"] = 'Westerly State Airport'
data$airport[data$airport == "XNA"] = 'Northwest Arkansas Regional Airport'
data$airport[data$airport == "YAK"] = 'Yakutat Airport'
data$airport[data$airport == "YUM"] = 'Yuma International Airport'
