data$city <- data$Origin

data$city[data$city == "ABE"] = 'Allentown'
data$city[data$city == "ABI"] = 'Abilene'
data$city[data$city == "ABQ"] = 'Albuquerque'
data$city[data$city == "ABR"] = 'Aberdeen'
data$city[data$city == "ABY"] = 'Albany'
data$city[data$city == "ACK"] = 'Nantucket'
data$city[data$city == "ACT"] = 'Waco'
data$city[data$city == "ACV"] = 'Arcata/Eureka'
data$city[data$city == "ACY"] = 'Atlantic City'
data$city[data$city == "ADK"] = 'Adak'
data$city[data$city == "ADQ"] = 'Kodiak'
data$city[data$city == "AEX"] = 'Alexandria'
data$city[data$city == "AGS"] = 'Augusta'
data$city[data$city == "AKN"] = 'King Salmon'
data$city[data$city == "ALB"] = 'Albany'
data$city[data$city == "ALO"] = 'Waterloo'
data$city[data$city == "AMA"] = 'Amarillo'
data$city[data$city == "ANC"] = 'Anchorage'
data$city[data$city == "APN"] = 'Alpena'
data$city[data$city == "ASE"] = 'Aspen'
data$city[data$city == "ATL"] = 'Atlanta'
data$city[data$city == "ATW"] = 'Appleton'
data$city[data$city == "AUS"] = 'Austin'
data$city[data$city == "AVL"] = 'Asheville'
data$city[data$city == "AVP"] = 'Wilkes-Barre/Scranton'
data$city[data$city == "AZO"] = 'Kalamazoo'
data$city[data$city == "BDL"] = 'Windsor Locks'
data$city[data$city == "BET"] = 'Bethel'
data$city[data$city == "BFL"] = 'Bakersfield'
data$city[data$city == "BGM"] = 'Binghamton'
data$city[data$city == "BGR"] = 'Bangor'
data$city[data$city == "BHM"] = 'Birmingham'
data$city[data$city == "BIL"] = 'Billings'
data$city[data$city == "BIS"] = 'Bismarck'
data$city[data$city == "BJI"] = 'Bemidji'
data$city[data$city == "BLI"] = 'Bellingham'
data$city[data$city == "BMI"] = 'Bloomington'
data$city[data$city == "BNA"] = 'Nashville'
data$city[data$city == "BOI"] = 'Boise'
data$city[data$city == "BOS"] = 'Boston'
data$city[data$city == "BPT"] = 'Beaumont/Port Arthur'
data$city[data$city == "BQK"] = 'Brunswick'
data$city[data$city == "BQN"] = 'Aguadilla'
data$city[data$city == "BRD"] = 'Brainerd'
data$city[data$city == "BRO"] = 'Brownsville'
data$city[data$city == "BRW"] = 'Barrow'
data$city[data$city == "BTM"] = 'Butte'
data$city[data$city == "BTR"] = 'Baton Rouge'
data$city[data$city == "BTV"] = 'Burlington'
data$city[data$city == "BUF"] = 'Buffalo'
data$city[data$city == "BUR"] = 'Burbank'
data$city[data$city == "BWI"] = 'Baltimore'
data$city[data$city == "BZN"] = 'Bozeman'
data$city[data$city == "CAE"] = 'Columbia'
data$city[data$city == "CAK"] = 'Akron'
data$city[data$city == "CDC"] = 'Cedar City'
data$city[data$city == "CDV"] = 'Cordova'
data$city[data$city == "CEC"] = 'Crescent City'
data$city[data$city == "CHA"] = 'Chattanooga'
data$city[data$city == "CHO"] = 'Charlottesville'
data$city[data$city == "CHS"] = 'Charleston'
data$city[data$city == "CID"] = 'Cedar Rapids'
data$city[data$city == "CIU"] = 'Sault Ste. Marie'
data$city[data$city == "CLD"] = 'San Diego'
data$city[data$city == "CLE"] = 'Cleveland'
data$city[data$city == "CLL"] = 'College Station'
data$city[data$city == "CLT"] = 'Charlotte'
data$city[data$city == "CMH"] = 'Columbus'
data$city[data$city == "CMI"] = 'Champaign/Urbana'
data$city[data$city == "CMX"] = 'Hancock'
data$city[data$city == "CNY"] = 'Moab'
data$city[data$city == "COD"] = 'Cody'
data$city[data$city == "COS"] = 'Colorado Springs'
data$city[data$city == "COU"] = 'Columbia'
data$city[data$city == "CPR"] = 'Casper'
data$city[data$city == "CRP"] = 'Corpus Christi'
data$city[data$city == "CRW"] = 'Charleston'
data$city[data$city == "CSG"] = 'Columbus'
data$city[data$city == "CVG"] = 'Covington'
data$city[data$city == "CWA"] = 'Mosinee'
data$city[data$city == "DAB"] = 'Daytona Beach'
data$city[data$city == "DAL"] = 'Dallas'
data$city[data$city == "DAY"] = 'Dayton'
data$city[data$city == "DBQ"] = 'Dubuque'
data$city[data$city == "DCA"] = 'Arlington'
data$city[data$city == "DEN"] = 'Denver'
data$city[data$city == "DFW"] = 'Dallas-Fort Worth'
data$city[data$city == "DHN"] = 'Dothan'
data$city[data$city == "DIK"] = 'Dickinson'
data$city[data$city == "DLG"] = 'Dillingham'
data$city[data$city == "DLH"] = 'Duluth'
data$city[data$city == "DRO"] = 'Durango'
data$city[data$city == "DSM"] = 'Des Moines'
data$city[data$city == "DTW"] = 'Detroit'
data$city[data$city == "DVL"] = 'Devils Lake'
data$city[data$city == "EAU"] = 'Eau Claire'
data$city[data$city == "ECP"] = 'Panama City'
data$city[data$city == "EGE"] = 'Eagle'
data$city[data$city == "EKO"] = 'Elko'
data$city[data$city == "ELM"] = 'Elmira'
data$city[data$city == "ELP"] = 'El Paso'
data$city[data$city == "ERI"] = 'Erie'
data$city[data$city == "ESC"] = 'Escanaba'
data$city[data$city == "EUG"] = 'Eugene'
data$city[data$city == "EVV"] = 'Evansville'
data$city[data$city == "EWN"] = 'New Bern'
data$city[data$city == "EWR"] = 'Newark'
data$city[data$city == "EYW"] = 'Key West'
data$city[data$city == "FAI"] = 'Fairbanks'
data$city[data$city == "FAR"] = 'Fargo'
data$city[data$city == "FAT"] = 'Fresno'
data$city[data$city == "FAY"] = 'Fayetteville'
data$city[data$city == "FCA"] = 'Kalispell'
data$city[data$city == "FLG"] = 'Flagstaff'
data$city[data$city == "FLL"] = 'Ft. Lauderdale'
data$city[data$city == "FNT"] = 'Flint'
data$city[data$city == "FSD"] = 'Sioux Falls'
data$city[data$city == "FSM"] = 'Fort Smith'
data$city[data$city == "FWA"] = 'Fort Wayne'
data$city[data$city == "GCC"] = 'Gillette'
data$city[data$city == "GCK"] = 'Garden City'
data$city[data$city == "GEG"] = 'Spokane'
data$city[data$city == "GFK"] = 'Grand Forks'
data$city[data$city == "GGG"] = 'Longview'
data$city[data$city == "GJT"] = 'Grand Junction'
data$city[data$city == "GNV"] = 'Gainesville'
data$city[data$city == "GPT"] = 'Gulfport-Biloxi'
data$city[data$city == "GRB"] = 'Green Bay'
data$city[data$city == "GRI"] = 'Grand Island'
data$city[data$city == "GRK"] = 'Killeen'
data$city[data$city == "GRR"] = 'Grand Rapids'
data$city[data$city == "GSO"] = 'Greensboro'
data$city[data$city == "GSP"] = 'Greer'
data$city[data$city == "GST"] = 'Gustavus'
data$city[data$city == "GTF"] = 'Great Falls'
data$city[data$city == "GTR"] = 'Columbus-Starkville-West Point'
data$city[data$city == "GUC"] = 'Gunnison'
data$city[data$city == "GUM"] = 'Agana'
data$city[data$city == "HDN"] = 'Hayden'
data$city[data$city == "HIB"] = 'Hibbing'
data$city[data$city == "HLN"] = 'Helena'
data$city[data$city == "HNL"] = 'Honolulu'
data$city[data$city == "HOB"] = 'Hobbs'
data$city[data$city == "HOU"] = 'Houston'
data$city[data$city == "HPN"] = 'White Plains'
data$city[data$city == "HRL"] = 'Harlingen'
data$city[data$city == "HSV"] = 'Huntsville'
data$city[data$city == "HYA"] = 'Hyannis'
data$city[data$city == "HYS"] = 'Hays'
data$city[data$city == "IAD"] = 'Chantilly'
data$city[data$city == "IAG"] = 'Niagara Falls'
data$city[data$city == "IAH"] = 'Houston'
data$city[data$city == "ICT"] = 'Wichita'
data$city[data$city == "IDA"] = 'Idaho Falls'
data$city[data$city == "ILG"] = 'Wilmington'
data$city[data$city == "ILM"] = 'Wilmington'
data$city[data$city == "IMT"] = 'Iron Mountain/Kingsford'
data$city[data$city == "IND"] = 'Indianapolis'
data$city[data$city == "INL"] = 'International Falls'
data$city[data$city == "ISN"] = 'Williston'
data$city[data$city == "ISP"] = 'Islip'
data$city[data$city == "ITH"] = 'Ithaca'
data$city[data$city == "ITO"] = 'Hilo'
data$city[data$city == "JAC"] = 'Jackson'
data$city[data$city == "JAN"] = 'Jackson'
data$city[data$city == "JAX"] = 'Jacksonville'
data$city[data$city == "JFK"] = 'New York'
data$city[data$city == "JLN"] = 'Joplin'
data$city[data$city == "JMS"] = 'Jamestown'
data$city[data$city == "JNU"] = 'Juneau'
data$city[data$city == "KOA"] = 'Kailua/Kona'
data$city[data$city == "KTN"] = 'Ketchikan'
data$city[data$city == "LAN"] = 'Lansing'
data$city[data$city == "LAR"] = 'Laramie'
data$city[data$city == "LAS"] = 'Las Vegas'
data$city[data$city == "LAW"] = 'Lawton'
data$city[data$city == "LAX"] = 'Los Angeles'
data$city[data$city == "LBB"] = 'Lubbock'
data$city[data$city == "LBE"] = 'Latrobe'
data$city[data$city == "LCH"] = 'Lake Charles'
data$city[data$city == "LEX"] = 'Lexington'
data$city[data$city == "LFT"] = 'Lafayette'
data$city[data$city == "LGA"] = 'New York'
data$city[data$city == "LGB"] = 'Long Beach'
data$city[data$city == "LIH"] = 'Lihue'
data$city[data$city == "LIT"] = 'Little Rock'
data$city[data$city == "LNK"] = 'Lincoln'
data$city[data$city == "LRD"] = 'Laredo'
data$city[data$city == "LSE"] = 'La Crosse'
data$city[data$city == "LWS"] = 'Lewiston'
data$city[data$city == "MAF"] = 'Midland'
data$city[data$city == "MBS"] = 'Saginaw'
data$city[data$city == "MCI"] = 'Kansas City'
data$city[data$city == "MCO"] = 'Orlando'
data$city[data$city == "MDT"] = 'Harrisburg'
data$city[data$city == "MDW"] = 'Chicago'
data$city[data$city == "MEI"] = 'Meridian'
data$city[data$city == "MEM"] = 'Memphis'
data$city[data$city == "MFE"] = 'McAllen'
data$city[data$city == "MFR"] = 'Medford'
data$city[data$city == "MGM"] = 'Montgomery'
data$city[data$city == "MHK"] = 'Manhattan'
data$city[data$city == "MHT"] = 'Manchester'
data$city[data$city == "MIA"] = 'Miami'
data$city[data$city == "MKE"] = 'Milwaukee'
data$city[data$city == "MKG"] = 'Muskegon'
data$city[data$city == "MLB"] = 'Melbourne'
data$city[data$city == "MLI"] = 'Moline'
data$city[data$city == "MLU"] = 'Monroe'
data$city[data$city == "MMH"] = 'Mammoth Lakes'
data$city[data$city == "MOB"] = 'Mobile'
data$city[data$city == "MOT"] = 'Minot'
data$city[data$city == "MQT"] = 'Marquette'
data$city[data$city == "MRY"] = 'Monterey'
data$city[data$city == "MSN"] = 'Madison'
data$city[data$city == "MSO"] = 'Missoula'
data$city[data$city == "MSP"] = 'Minneapolis'
data$city[data$city == "MSY"] = 'New Orleans'
data$city[data$city == "MTJ"] = 'Montrose'
data$city[data$city == "MVY"] = 'Marthas Vineyard'
data$city[data$city == "MYR"] = 'Myrtle Beach'
data$city[data$city == "OAJ"] = 'Jacksonville'
data$city[data$city == "OAK"] = 'Oakland'
data$city[data$city == "OGG"] = 'Kahului'
data$city[data$city == "OKC"] = 'Oklahoma City'
data$city[data$city == "OMA"] = 'Omaha'
data$city[data$city == "OME"] = 'Nome'
data$city[data$city == "ONT"] = 'Ontario'
data$city[data$city == "ORD"] = 'Chicago'
data$city[data$city == "ORF"] = 'Norfolk'
data$city[data$city == "ORH"] = 'Worcester'
data$city[data$city == "OTH"] = 'North Bend'
data$city[data$city == "OTZ"] = 'Kotzebue'
data$city[data$city == "PAH"] = 'Paducah'
data$city[data$city == "PBG"] = 'Plattsburgh'
data$city[data$city == "PBI"] = 'West Palm Beach'
data$city[data$city == "PDX"] = 'Portland'
data$city[data$city == "PHF"] = 'Newport News'
data$city[data$city == "PHL"] = 'Philadelphia'
data$city[data$city == "PHX"] = 'Phoenix'
data$city[data$city == "PIA"] = 'Peoria'
data$city[data$city == "PIB"] = 'Hattiesburg-Laurel'
data$city[data$city == "PIH"] = 'Pocatello'
data$city[data$city == "PIT"] = 'Pittsburgh'
data$city[data$city == "PLN"] = 'Pellston'
data$city[data$city == "PNS"] = 'Pensacola'
data$city[data$city == "PPG"] = 'Pago Pago'
data$city[data$city == "PSC"] = 'Pasco'
data$city[data$city == "PSE"] = 'Ponce'
data$city[data$city == "PSG"] = 'Petersburg'
data$city[data$city == "PSP"] = 'Palm Springs'
data$city[data$city == "PUB"] = 'Pueblo'
data$city[data$city == "PVD"] = 'Providence'
data$city[data$city == "PWM"] = 'Portland'
data$city[data$city == "RAP"] = 'Rapid City'
data$city[data$city == "RDD"] = 'Redding'
data$city[data$city == "RDM"] = 'Redmond'
data$city[data$city == "RDU"] = 'Raleigh'
data$city[data$city == "RHI"] = 'Rhinelander'
data$city[data$city == "RIC"] = 'Richmond'
data$city[data$city == "RKS"] = 'Rock Springs'
data$city[data$city == "RNO"] = 'Reno'
data$city[data$city == "ROA"] = 'Roanoke'
data$city[data$city == "ROC"] = 'Rochester'
data$city[data$city == "ROW"] = 'Roswell'
data$city[data$city == "RST"] = 'Rochester'
data$city[data$city == "RSW"] = 'Ft. Myers'
data$city[data$city == "SAF"] = 'Santa Fe'
data$city[data$city == "SAN"] = 'San Diego'
data$city[data$city == "SAT"] = 'San Antonio'
data$city[data$city == "SAV"] = 'Savannah'
data$city[data$city == "SBA"] = 'Santa Barbara'
data$city[data$city == "SBN"] = 'South Bend'
data$city[data$city == "SBP"] = 'San Luis Obispo'
data$city[data$city == "SCC"] = 'Deadhorse'
data$city[data$city == "SCE"] = 'State College'
data$city[data$city == "SDF"] = 'Louisville'
data$city[data$city == "SEA"] = 'Seattle'
data$city[data$city == "SFO"] = 'San Francisco'
data$city[data$city == "SGF"] = 'Springfield'
data$city[data$city == "SGU"] = 'St George'
data$city[data$city == "SHV"] = 'Shreveport'
data$city[data$city == "SIT"] = 'Sitka'
data$city[data$city == "SJC"] = 'San Jose'
data$city[data$city == "SJT"] = 'San Angelo'
data$city[data$city == "SJU"] = 'San Juan'
data$city[data$city == "SLC"] = 'Salt Lake City'
data$city[data$city == "SMF"] = 'Sacramento'
data$city[data$city == "SMX"] = 'Santa Maria'
data$city[data$city == "SNA"] = 'Santa Ana'
data$city[data$city == "SPI"] = 'Springfield'
data$city[data$city == "SPS"] = 'Wichita Falls'
data$city[data$city == "SRQ"] = 'Sarasota'
data$city[data$city == "STC"] = 'St Cloud'
data$city[data$city == "STL"] = 'St Louis'
data$city[data$city == "STT"] = 'Charlotte Amalie'
data$city[data$city == "STX"] = 'Christiansted'
data$city[data$city == "SUN"] = 'Hailey'
data$city[data$city == "SUX"] = 'Sioux City'
data$city[data$city == "SWF"] = 'Newburgh'
data$city[data$city == "SYR"] = 'Syracuse'
data$city[data$city == "TLH"] = 'Tallahassee'
data$city[data$city == "TOL"] = 'Toledo'
data$city[data$city == "TPA"] = 'Tampa'
data$city[data$city == "TRI"] = 'Bristol'
data$city[data$city == "TTN"] = 'Trenton'
data$city[data$city == "TUL"] = 'Tulsa'
data$city[data$city == "TUS"] = 'Tucson'
data$city[data$city == "TVC"] = 'Traverse City'
data$city[data$city == "TWF"] = 'Twin Falls'
data$city[data$city == "TXK"] = 'Texarkana'
data$city[data$city == "TYR"] = 'Tyler'
data$city[data$city == "TYS"] = 'Knoxville'
data$city[data$city == "UST"] = 'St. Augustine'
data$city[data$city == "VEL"] = 'Vernal'
data$city[data$city == "VLD"] = 'Valdosta'
data$city[data$city == "VPS"] = 'Valparaiso'
data$city[data$city == "WRG"] = 'Wrangell'
data$city[data$city == "WYS"] = 'West Yellowstone'
data$city[data$city == "XNA"] = 'Fayetteville/Springdale/Rogers'
data$city[data$city == "YAK"] = 'Yakutat'
data$city[data$city == "YUM"] = 'Yuma'
